spring.main:
    web-application-type: none
    banner-mode: 'off'
    log-startup-info: false
oidc:
    apiKey: 'vg-app'
    apiSecret: 'HpcJB1VlPTQ8cIivFbduTdv0mFmGv1w6'
    callbackurl: 'http://localhost:8090/openid-showcase'
    baseurl: 'http://localhost:8080'
    realm: 'aro-realm'
